# Generated by Django 5.1.2 on 2024-10-21 10:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Envanter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ucak_turu', models.CharField(choices=[('TB2', 'TB2'), ('TB3', 'TB3'), ('AKINCI', 'AKINCI'), ('KIZILELMA', 'KIZILELMA')], max_length=10)),
                ('stok_miktari', models.IntegerField(default=0)),
                ('kanat_gereksinimi', models.IntegerField(default=2)),
                ('govde_gereksinimi', models.IntegerField(default=1)),
                ('kuyruk_gereksinimi', models.IntegerField(default=1)),
                ('aviyonik_gereksinimi', models.IntegerField(default=1)),
            ],
        ),
    ]
