# Generated by Django 5.1.2 on 2024-10-21 10:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Parca',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('isim', models.CharField(max_length=100)),
                ('ucak_turu', models.CharField(choices=[('TB2', 'TB2'), ('TB3', 'TB3'), ('AKINCI', 'AKINCI'), ('KIZILELMA', 'KIZILELMA')], max_length=10)),
                ('parca_turu', models.CharField(choices=[('kanat', 'Kanat'), ('govde', 'Gövde'), ('kuyruk', 'Kuyruk'), ('aviyonik', 'Aviyonik')], max_length=50)),
                ('stok_sayisi', models.IntegerField(default=0)),
                ('geri_donusen', models.IntegerField(default=0)),
            ],
        ),
    ]
