# Generated by Django 5.1.2 on 2024-10-21 10:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Takim',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('isim', models.CharField(max_length=100)),
                ('parca_turu', models.CharField(choices=[('kanat', 'Kanat Takımı'), ('govde', 'Gövde Takımı'), ('kuyruk', 'Kuyruk Takımı'), ('aviyonik', 'Aviyonik Takımı'), ('montaj', 'Montaj Takımı')], max_length=50)),
            ],
        ),
    ]
